# Arrow keys
UP          add volume  5                      # ignore keybinds for
DOWN        add volume -5                      # directional keys
LEFT        seek -5        
RIGHT       seek 5      
        
SPACE       cycle pause                 # toggle pause
ENTER       cycle pause                 # toggle pause
        
META+UP     add volume  5               # change volume
META+DOWN   add volume -5               
META+RIGHT  seek  60                    # 1 minute seeks
META+LEFT   seek -60        
        
SHIFT+UP    ignore        
SHIFT+DOWN  ignore        
SHIFT+RIGHT frame-step             
SHIFT+LEFT  frame-back-step

ALT+UP      ignore
ALT+DOWN    ignore
ALT+RIGHT   seek  10 - exact            # 10 second seeks
ALT+LEFT    seek -10 - exact

AXIS_UP     add volume  5                # mouse scrolls
AXIS_DOWN   add volume  -5         
AXIS_RIGHT  ignore        
AXIS_LEFT   ignore 


# special character key maps

~           cycle ontop                 # keep mpv window on top of others



# alphabet keymaps

g           add sub-delay   -0.1        # subtitle delays (100ms)
h           add sub-delay   +0.1
j           add audio-delay -0.1        # audio delays (100ms)
k           add audio-delay +0.1        
q			ignore
Q			ignore

o           cycle video-unscaled        # scale/unscale video
O           cycle video-unscaled
a           cycle_values video-aspect "16:9" "4:3" "2.35:1" "-1"

t           show_progress               # show video progress bar
T           osd                         # cycle through osd mode
v           cycle sub                   # cycle through subs
b           cycle audio                 # cycle through audio streams
m           cycle mute                  # toggle mute

= 			add sub-scale +0.1
- 			add sub-scale -0.1
+ 			add sub-pos +1
_ 			add sub-pos -1

# Swap default screenshot button

S screenshot                           # take a screenshot of the video in its original resolution with subtitles
s screenshot video                     # take a screenshot of the video in its original resolution without subtitles

